apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: fastapi-prod
spec:
  interval: 5m
  releaseName: fastapi-prod

  chart:
    spec:
      chart: ./fastapi-app
      sourceRef:
        kind: GitRepository
        name: fastapi-helm-repo
        # namespace: flaskapi-prod

  values:
    image:
      repository: ghcr.io/pauldjmetsi/fastapi-docker-app
      tag: "2c173431aee1e0ca5d176e323d57d970312d0d48"

    env:
      APP_ENV: prod
      APP_NAME: fastapi-prod
      FEATURE_FLAG: "true"

    secret:
      API_KEY: "prod-secret"

    ingress:
      enabled: true
      className: kommander-traefik
      issuer: selfsigned-issuer
      appName: fastapi
      environment: prod
      nipDomain: "10.2.0.151.nip.io"
      tlsSecret: fastapi-prod-tls